site_name: Domain-SC Documentation
site_description: Documentation for the Domain-SC system
site_author: Domain-SC Team

repo_name: Domain-SC
repo_url: https://github.com/yourusername/Domain-SC

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.annotate
    - content.tabs.link

nav:
  - Home: index.md
  - Getting Started: 
    - Installation: guides/installation.md
    - Quick Start: guides/quick-start.md
  - User Guide: guides/user-guide.md
  - Architecture:
    - System Overview: architecture/overview.md
    - Components: architecture/components.md
    - Workflows: architecture/workflows.md
  - API Reference:
    - Services: api/services.md
    - Agents: api/agents.md
    - Prompt System: api/prompts.md
  - Development:
    - Contributing: development/CONTRIBUTING.md
    - Code Standards: development/code-standards.md
    - Development Setup: development/setup.md
  - Examples:
    - Basic Usage: examples/basic.md
    - Advanced Scenarios: examples/advanced.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - footnotes
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            docstring_style: google
          rendering:
            show_source: true
  - autorefs